steps:
# use clone from github
  - name: gcr.io/cloud-builders/git
    args: ['clone', '-b', '${_BRANCH}', '--single-branch', '--depth', '1', 'https://github.com/wgryglas/reDocWriter.git']

  - name: gcr.io/${PROJECT_ID}/redocwriter-build:latest
    args: ["server_bundle_config.spec"]
    dir: reDocWriter

  - name: gcr.io/${PROJECT_ID}/redocwriter-build:latest
    args: ["app_bundle_config.spec"]
    dir: reDocWriter

artifacts:
  objects:
    location: 'gs://download.wgryglas.pl/reDocWriter'
    paths: ['reDocWriter/dist/reDocWriter']

substitutions:
  _BRANCH: master
#  _SUB_DOMAIN: www



# To build using gcloud tools run command (make sure that appropriate project is specified):
# gcloud builds submit --config cloudbuild.yaml --no-source